name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código del repositorio
      - uses: actions/checkout@v3

      # 2. Instalar Java (requerido para Android builds)
      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Instalar Flutter SDK
      - name: Instalar Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'

      # 4. Verificar instalación de Flutter
      - name: Verificar Flutter
        run: flutter doctor -v

      # 5. Obtener dependencias
      - name: Instalar dependencias
        run: flutter pub get

      # 6. Analizar código (detectar errores de sintaxis)
      - name: Analizar código Dart
        run: flutter analyze

      # 7. Ejecutar tests unitarios
      - name: Ejecutar tests
        run: flutter test

      # 8. Verificar que la app compile para Android
      - name: Build APK
        run: flutter build apk --debug

      # 9. Verificar archivos generados
      - name: Verificar build exitoso
        run: |
          if [ -f "build/app/outputs/flutter-apk/app-debug.apk" ]; then
            echo "✅ APK generado correctamente"
            ls -la build/app/outputs/flutter-apk/
          else
            echo "❌ Error: APK no fue generado"
            exit 1
          fi